In [1]:
import pandas as pd

df = pd.read_csv('df_model_sans_meteo.csv')

In [2]:
from pycaret.regression import *

s = setup(df, target='box_office_first_week',session_id=123)

In [3]:
models = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .           10:16:06
Status     . . . . . . . . . . . . . . . . . .   Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Linear Regression

In [4]:
df_perf = pull(models)
display(df_perf)

,Model,MAE,MSE,RMSE,R2,RMSLE,MAPE,TT (Sec)
et,Extra Trees Regressor,96637.5029,4.681353e+10,213190.8465,0.5137,1.3845,7.9888,0.813
catboost,CatBoost Regressor,96120.7999,4.781830e+10,215454.6090,0.5018,1.5114,9.3459,4.449
rf,Random Forest Regressor,99671.2381,5.004292e+10,220723.4149,0.4771,1.4028,10.3926,1.088
lightgbm,Light Gradient Boosting Machine,98824.1584,5.074197e+10,222041.3702,0.4706,1.4976,8.7335,0.180
gbr,Gradient Boosting Regressor,102507.1118,5.150261e+10,223731.2781,0.4607,1.6397,14.2688,0.418
ridge,Ridge Regression,120065.3162,5.364131e+10,228232.6831,0.4422,2.0936,36.0091,0.112
lr,Linear Regression,120114.1542,5.366931e+10,228302.6954,0.4418,2.0940,35.9487,0.488
lasso,Lasso Regression,120111.2739,5.366718e+10,228297.7026,0.4418,2.0936,35.9433,0.109
llar,Lasso Least Angle Regression,120111.2591,5.366719e+10,228297.7177,0.4418,2.0936,35.9431,0.100
lar,Least Angle Regression,120593.6740,5.374920e+10,228482.5681,0.4409,2.0972,36.1762,0.098
xgboost,Extreme Gradient Boosting,102165.5480,5.295727e+10,227790.9897,0.4352,1.5449,11.3887,0.525
en,Elastic Net,123840.9838,5.482959e+10,230549.9185,0.4313,2.1737,37.6809,0.103
br,Bayesian Ridge,124567.0866,5.567620e+10,232368.4967,0.4215,2.1734,35.8756,0.099
omp,Orthogonal Matching Pursuit,124039.1951,5.732772e+10,235925.2096,0.4025,2.1031,31.9223,0.100
huber,Huber Regressor,102493.9551,5.989496e+10,240463.5504,0.3850,1.6057,9.4686,0.153
knn,K Neighbors Regressor,121620.5511,6.731033e+10,255760.7080,0.2899,1.7345,19.3151,0.106
dt,Decision Tree Regressor,128830.8276,8.081578e+10,283010.2317,0.0914,1.6812,6.8735,0.121
dummy,Dummy Regressor,175285.4936,9.748850e+10,307522.4352,-0.0053,2.7181,86.9524,0.096
ada,AdaBoost Regressor,275108.4895,1.193622e+11,344288.9314,-0.3362,2.9100,100.2616,0.269
par,Passive Aggressive Regressor,263271.7047,6.371115e+11,585469.7753,-5.0140,2.0757,29.9874,0.100

In [5]:
import pandas as pd

df = pd.read_csv('df_model.csv')

In [6]:
from pycaret.regression import *

s = setup(df, target='box_office_first_week',session_id=123)

In [7]:
models = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .           11:06:25
Status     . . . . . . . . . . . . . . . . . .  Loading Estimator
Estimator  . . . . . . . . . . . . . . . . . .  Compiling Library